=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.51-SNAPSHOT

=end

require 'date'

module GlobalEventTechnologyApiClient
  class ExternalSiteModel
    attr_accessor :unit_id

    attr_accessor :name

    attr_accessor :type

    attr_accessor :enable_pos_targets

    attr_accessor :menu_id

    attr_accessor :ac_area_id

    attr_accessor :ac_area_exit_id

    attr_accessor :menu_item_id

    attr_accessor :enable_payout

    attr_accessor :tickets_use_cart

    attr_accessor :tickets_cart_max_size

    attr_accessor :tickets_allow_barcode_by_keyboard

    attr_accessor :ticket_site_mapping_label_config

    attr_accessor :tickets_swap_to_chip

    attr_accessor :tickets_allow_search

    attr_accessor :tickets_emit_access_check

    attr_accessor :ac_check_sell_product

    attr_accessor :ac_check_use_turnstyle

    attr_accessor :self_service_card_payment_type_id

    attr_accessor :self_service_cash_payment_type_id

    attr_accessor :self_service_cashless_payment_type_id

    attr_accessor :payment_type_ids

    attr_accessor :chip_ids

    attr_accessor :tip_config_id

    attr_accessor :enable_master_barcodes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'unit_id' => :'unitId',
        :'name' => :'name',
        :'type' => :'type',
        :'enable_pos_targets' => :'enablePosTargets',
        :'menu_id' => :'menuId',
        :'ac_area_id' => :'acAreaId',
        :'ac_area_exit_id' => :'acAreaExitId',
        :'menu_item_id' => :'menuItemId',
        :'enable_payout' => :'enablePayout',
        :'tickets_use_cart' => :'ticketsUseCart',
        :'tickets_cart_max_size' => :'ticketsCartMaxSize',
        :'tickets_allow_barcode_by_keyboard' => :'ticketsAllowBarcodeByKeyboard',
        :'ticket_site_mapping_label_config' => :'ticketSiteMappingLabelConfig',
        :'tickets_swap_to_chip' => :'ticketsSwapToChip',
        :'tickets_allow_search' => :'ticketsAllowSearch',
        :'tickets_emit_access_check' => :'ticketsEmitAccessCheck',
        :'ac_check_sell_product' => :'acCheckSellProduct',
        :'ac_check_use_turnstyle' => :'acCheckUseTurnstyle',
        :'self_service_card_payment_type_id' => :'selfServiceCardPaymentTypeId',
        :'self_service_cash_payment_type_id' => :'selfServiceCashPaymentTypeId',
        :'self_service_cashless_payment_type_id' => :'selfServiceCashlessPaymentTypeId',
        :'payment_type_ids' => :'paymentTypeIds',
        :'chip_ids' => :'chipIds',
        :'tip_config_id' => :'tipConfigId',
        :'enable_master_barcodes' => :'enableMasterBarcodes'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'unit_id' => :'String',
        :'name' => :'String',
        :'type' => :'ExternalSiteTypeModel',
        :'enable_pos_targets' => :'BOOLEAN',
        :'menu_id' => :'String',
        :'ac_area_id' => :'String',
        :'ac_area_exit_id' => :'String',
        :'menu_item_id' => :'String',
        :'enable_payout' => :'BOOLEAN',
        :'tickets_use_cart' => :'BOOLEAN',
        :'tickets_cart_max_size' => :'Integer',
        :'tickets_allow_barcode_by_keyboard' => :'BOOLEAN',
        :'ticket_site_mapping_label_config' => :'ExternalSiteTicketTypeLabelModel',
        :'tickets_swap_to_chip' => :'BOOLEAN',
        :'tickets_allow_search' => :'BOOLEAN',
        :'tickets_emit_access_check' => :'BOOLEAN',
        :'ac_check_sell_product' => :'BOOLEAN',
        :'ac_check_use_turnstyle' => :'BOOLEAN',
        :'self_service_card_payment_type_id' => :'String',
        :'self_service_cash_payment_type_id' => :'String',
        :'self_service_cashless_payment_type_id' => :'String',
        :'payment_type_ids' => :'Array<String>',
        :'chip_ids' => :'Array<String>',
        :'tip_config_id' => :'String',
        :'enable_master_barcodes' => :'BOOLEAN'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'unitId')
        self.unit_id = attributes[:'unitId']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.has_key?(:'enablePosTargets')
        self.enable_pos_targets = attributes[:'enablePosTargets']
      end

      if attributes.has_key?(:'menuId')
        self.menu_id = attributes[:'menuId']
      end

      if attributes.has_key?(:'acAreaId')
        self.ac_area_id = attributes[:'acAreaId']
      end

      if attributes.has_key?(:'acAreaExitId')
        self.ac_area_exit_id = attributes[:'acAreaExitId']
      end

      if attributes.has_key?(:'menuItemId')
        self.menu_item_id = attributes[:'menuItemId']
      end

      if attributes.has_key?(:'enablePayout')
        self.enable_payout = attributes[:'enablePayout']
      end

      if attributes.has_key?(:'ticketsUseCart')
        self.tickets_use_cart = attributes[:'ticketsUseCart']
      end

      if attributes.has_key?(:'ticketsCartMaxSize')
        self.tickets_cart_max_size = attributes[:'ticketsCartMaxSize']
      end

      if attributes.has_key?(:'ticketsAllowBarcodeByKeyboard')
        self.tickets_allow_barcode_by_keyboard = attributes[:'ticketsAllowBarcodeByKeyboard']
      end

      if attributes.has_key?(:'ticketSiteMappingLabelConfig')
        self.ticket_site_mapping_label_config = attributes[:'ticketSiteMappingLabelConfig']
      end

      if attributes.has_key?(:'ticketsSwapToChip')
        self.tickets_swap_to_chip = attributes[:'ticketsSwapToChip']
      end

      if attributes.has_key?(:'ticketsAllowSearch')
        self.tickets_allow_search = attributes[:'ticketsAllowSearch']
      end

      if attributes.has_key?(:'ticketsEmitAccessCheck')
        self.tickets_emit_access_check = attributes[:'ticketsEmitAccessCheck']
      end

      if attributes.has_key?(:'acCheckSellProduct')
        self.ac_check_sell_product = attributes[:'acCheckSellProduct']
      end

      if attributes.has_key?(:'acCheckUseTurnstyle')
        self.ac_check_use_turnstyle = attributes[:'acCheckUseTurnstyle']
      end

      if attributes.has_key?(:'selfServiceCardPaymentTypeId')
        self.self_service_card_payment_type_id = attributes[:'selfServiceCardPaymentTypeId']
      end

      if attributes.has_key?(:'selfServiceCashPaymentTypeId')
        self.self_service_cash_payment_type_id = attributes[:'selfServiceCashPaymentTypeId']
      end

      if attributes.has_key?(:'selfServiceCashlessPaymentTypeId')
        self.self_service_cashless_payment_type_id = attributes[:'selfServiceCashlessPaymentTypeId']
      end

      if attributes.has_key?(:'paymentTypeIds')
        if (value = attributes[:'paymentTypeIds']).is_a?(Array)
          self.payment_type_ids = value
        end
      end

      if attributes.has_key?(:'chipIds')
        if (value = attributes[:'chipIds']).is_a?(Array)
          self.chip_ids = value
        end
      end

      if attributes.has_key?(:'tipConfigId')
        self.tip_config_id = attributes[:'tipConfigId']
      end

      if attributes.has_key?(:'enableMasterBarcodes')
        self.enable_master_barcodes = attributes[:'enableMasterBarcodes']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @unit_id.nil?
        invalid_properties.push('invalid value for "unit_id", unit_id cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @enable_pos_targets.nil?
        invalid_properties.push('invalid value for "enable_pos_targets", enable_pos_targets cannot be nil.')
      end

      if @enable_payout.nil?
        invalid_properties.push('invalid value for "enable_payout", enable_payout cannot be nil.')
      end

      if @tickets_use_cart.nil?
        invalid_properties.push('invalid value for "tickets_use_cart", tickets_use_cart cannot be nil.')
      end

      if @tickets_allow_barcode_by_keyboard.nil?
        invalid_properties.push('invalid value for "tickets_allow_barcode_by_keyboard", tickets_allow_barcode_by_keyboard cannot be nil.')
      end

      if @tickets_swap_to_chip.nil?
        invalid_properties.push('invalid value for "tickets_swap_to_chip", tickets_swap_to_chip cannot be nil.')
      end

      if @tickets_allow_search.nil?
        invalid_properties.push('invalid value for "tickets_allow_search", tickets_allow_search cannot be nil.')
      end

      if @tickets_emit_access_check.nil?
        invalid_properties.push('invalid value for "tickets_emit_access_check", tickets_emit_access_check cannot be nil.')
      end

      if @ac_check_sell_product.nil?
        invalid_properties.push('invalid value for "ac_check_sell_product", ac_check_sell_product cannot be nil.')
      end

      if @ac_check_use_turnstyle.nil?
        invalid_properties.push('invalid value for "ac_check_use_turnstyle", ac_check_use_turnstyle cannot be nil.')
      end

      if @enable_master_barcodes.nil?
        invalid_properties.push('invalid value for "enable_master_barcodes", enable_master_barcodes cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @unit_id.nil?
      return false if @type.nil?
      return false if @enable_pos_targets.nil?
      return false if @enable_payout.nil?
      return false if @tickets_use_cart.nil?
      return false if @tickets_allow_barcode_by_keyboard.nil?
      return false if @tickets_swap_to_chip.nil?
      return false if @tickets_allow_search.nil?
      return false if @tickets_emit_access_check.nil?
      return false if @ac_check_sell_product.nil?
      return false if @ac_check_use_turnstyle.nil?
      return false if @enable_master_barcodes.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          unit_id == o.unit_id &&
          name == o.name &&
          type == o.type &&
          enable_pos_targets == o.enable_pos_targets &&
          menu_id == o.menu_id &&
          ac_area_id == o.ac_area_id &&
          ac_area_exit_id == o.ac_area_exit_id &&
          menu_item_id == o.menu_item_id &&
          enable_payout == o.enable_payout &&
          tickets_use_cart == o.tickets_use_cart &&
          tickets_cart_max_size == o.tickets_cart_max_size &&
          tickets_allow_barcode_by_keyboard == o.tickets_allow_barcode_by_keyboard &&
          ticket_site_mapping_label_config == o.ticket_site_mapping_label_config &&
          tickets_swap_to_chip == o.tickets_swap_to_chip &&
          tickets_allow_search == o.tickets_allow_search &&
          tickets_emit_access_check == o.tickets_emit_access_check &&
          ac_check_sell_product == o.ac_check_sell_product &&
          ac_check_use_turnstyle == o.ac_check_use_turnstyle &&
          self_service_card_payment_type_id == o.self_service_card_payment_type_id &&
          self_service_cash_payment_type_id == o.self_service_cash_payment_type_id &&
          self_service_cashless_payment_type_id == o.self_service_cashless_payment_type_id &&
          payment_type_ids == o.payment_type_ids &&
          chip_ids == o.chip_ids &&
          tip_config_id == o.tip_config_id &&
          enable_master_barcodes == o.enable_master_barcodes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [unit_id, name, type, enable_pos_targets, menu_id, ac_area_id, ac_area_exit_id, menu_item_id, enable_payout, tickets_use_cart, tickets_cart_max_size, tickets_allow_barcode_by_keyboard, ticket_site_mapping_label_config, tickets_swap_to_chip, tickets_allow_search, tickets_emit_access_check, ac_check_sell_product, ac_check_use_turnstyle, self_service_card_payment_type_id, self_service_cash_payment_type_id, self_service_cashless_payment_type_id, payment_type_ids, chip_ids, tip_config_id, enable_master_barcodes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = GlobalEventTechnologyApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
