=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.51-SNAPSHOT

=end

require 'date'

module GlobalEventTechnologyApiClient
  class ExternalApiTagChangeInfoModel
    attr_accessor :external_reference

    attr_accessor :update_date

    attr_accessor :reference_date

    attr_accessor :tag_session

    attr_accessor :transaction_id

    attr_accessor :tag_change_id

    attr_accessor :unit_id

    attr_accessor :site_id

    attr_accessor :cancellation_requested

    attr_accessor :status

    attr_accessor :items

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'external_reference' => :'externalReference',
        :'update_date' => :'updateDate',
        :'reference_date' => :'referenceDate',
        :'tag_session' => :'tagSession',
        :'transaction_id' => :'transactionId',
        :'tag_change_id' => :'tagChangeId',
        :'unit_id' => :'unitId',
        :'site_id' => :'siteId',
        :'cancellation_requested' => :'cancellationRequested',
        :'status' => :'status',
        :'items' => :'items'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'external_reference' => :'String',
        :'update_date' => :'DateTime',
        :'reference_date' => :'DateTime',
        :'tag_session' => :'String',
        :'transaction_id' => :'String',
        :'tag_change_id' => :'String',
        :'unit_id' => :'String',
        :'site_id' => :'String',
        :'cancellation_requested' => :'BOOLEAN',
        :'status' => :'ExternalApiChangeInfoStatusEnumModel',
        :'items' => :'Array<ExternalApiChangeItemInfoModel>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'externalReference')
        self.external_reference = attributes[:'externalReference']
      end

      if attributes.has_key?(:'updateDate')
        self.update_date = attributes[:'updateDate']
      end

      if attributes.has_key?(:'referenceDate')
        self.reference_date = attributes[:'referenceDate']
      end

      if attributes.has_key?(:'tagSession')
        self.tag_session = attributes[:'tagSession']
      end

      if attributes.has_key?(:'transactionId')
        self.transaction_id = attributes[:'transactionId']
      end

      if attributes.has_key?(:'tagChangeId')
        self.tag_change_id = attributes[:'tagChangeId']
      end

      if attributes.has_key?(:'unitId')
        self.unit_id = attributes[:'unitId']
      end

      if attributes.has_key?(:'siteId')
        self.site_id = attributes[:'siteId']
      end

      if attributes.has_key?(:'cancellationRequested')
        self.cancellation_requested = attributes[:'cancellationRequested']
      end

      if attributes.has_key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.has_key?(:'items')
        if (value = attributes[:'items']).is_a?(Array)
          self.items = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @update_date.nil?
        invalid_properties.push('invalid value for "update_date", update_date cannot be nil.')
      end

      if @reference_date.nil?
        invalid_properties.push('invalid value for "reference_date", reference_date cannot be nil.')
      end

      if @transaction_id.nil?
        invalid_properties.push('invalid value for "transaction_id", transaction_id cannot be nil.')
      end

      if @tag_change_id.nil?
        invalid_properties.push('invalid value for "tag_change_id", tag_change_id cannot be nil.')
      end

      if @unit_id.nil?
        invalid_properties.push('invalid value for "unit_id", unit_id cannot be nil.')
      end

      if @site_id.nil?
        invalid_properties.push('invalid value for "site_id", site_id cannot be nil.')
      end

      if @cancellation_requested.nil?
        invalid_properties.push('invalid value for "cancellation_requested", cancellation_requested cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @update_date.nil?
      return false if @reference_date.nil?
      return false if @transaction_id.nil?
      return false if @tag_change_id.nil?
      return false if @unit_id.nil?
      return false if @site_id.nil?
      return false if @cancellation_requested.nil?
      return false if @status.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          external_reference == o.external_reference &&
          update_date == o.update_date &&
          reference_date == o.reference_date &&
          tag_session == o.tag_session &&
          transaction_id == o.transaction_id &&
          tag_change_id == o.tag_change_id &&
          unit_id == o.unit_id &&
          site_id == o.site_id &&
          cancellation_requested == o.cancellation_requested &&
          status == o.status &&
          items == o.items
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [external_reference, update_date, reference_date, tag_session, transaction_id, tag_change_id, unit_id, site_id, cancellation_requested, status, items].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = GlobalEventTechnologyApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
