=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.51-SNAPSHOT

=end

require 'date'

module GlobalEventTechnologyApiClient
  class PublicTagStateModel
    attr_accessor :time_stamp

    attr_accessor :tag_nr

    attr_accessor :session_counter

    attr_accessor :manager_group

    attr_accessor :normal_credits

    attr_accessor :pure_gift_credits

    attr_accessor :pre_gift_credits

    attr_accessor :total_credits

    attr_accessor :credits_for_payout

    attr_accessor :system_flags

    attr_accessor :project_fields

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'time_stamp' => :'timeStamp',
        :'tag_nr' => :'tagNr',
        :'session_counter' => :'sessionCounter',
        :'manager_group' => :'managerGroup',
        :'normal_credits' => :'normalCredits',
        :'pure_gift_credits' => :'pureGiftCredits',
        :'pre_gift_credits' => :'preGiftCredits',
        :'total_credits' => :'totalCredits',
        :'credits_for_payout' => :'creditsForPayout',
        :'system_flags' => :'systemFlags',
        :'project_fields' => :'projectFields'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'time_stamp' => :'DateTime',
        :'tag_nr' => :'String',
        :'session_counter' => :'Integer',
        :'manager_group' => :'Integer',
        :'normal_credits' => :'String',
        :'pure_gift_credits' => :'String',
        :'pre_gift_credits' => :'String',
        :'total_credits' => :'String',
        :'credits_for_payout' => :'String',
        :'system_flags' => :'TagSystemFlagsModel',
        :'project_fields' => :'ProjectFieldsModel'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'timeStamp')
        self.time_stamp = attributes[:'timeStamp']
      end

      if attributes.has_key?(:'tagNr')
        self.tag_nr = attributes[:'tagNr']
      end

      if attributes.has_key?(:'sessionCounter')
        self.session_counter = attributes[:'sessionCounter']
      end

      if attributes.has_key?(:'managerGroup')
        self.manager_group = attributes[:'managerGroup']
      end

      if attributes.has_key?(:'normalCredits')
        self.normal_credits = attributes[:'normalCredits']
      end

      if attributes.has_key?(:'pureGiftCredits')
        self.pure_gift_credits = attributes[:'pureGiftCredits']
      end

      if attributes.has_key?(:'preGiftCredits')
        self.pre_gift_credits = attributes[:'preGiftCredits']
      end

      if attributes.has_key?(:'totalCredits')
        self.total_credits = attributes[:'totalCredits']
      end

      if attributes.has_key?(:'creditsForPayout')
        self.credits_for_payout = attributes[:'creditsForPayout']
      end

      if attributes.has_key?(:'systemFlags')
        self.system_flags = attributes[:'systemFlags']
      end

      if attributes.has_key?(:'projectFields')
        self.project_fields = attributes[:'projectFields']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @time_stamp.nil?
        invalid_properties.push('invalid value for "time_stamp", time_stamp cannot be nil.')
      end

      if @session_counter.nil?
        invalid_properties.push('invalid value for "session_counter", session_counter cannot be nil.')
      end

      if @manager_group.nil?
        invalid_properties.push('invalid value for "manager_group", manager_group cannot be nil.')
      end

      if @normal_credits.nil?
        invalid_properties.push('invalid value for "normal_credits", normal_credits cannot be nil.')
      end

      if @pure_gift_credits.nil?
        invalid_properties.push('invalid value for "pure_gift_credits", pure_gift_credits cannot be nil.')
      end

      if @pre_gift_credits.nil?
        invalid_properties.push('invalid value for "pre_gift_credits", pre_gift_credits cannot be nil.')
      end

      if @total_credits.nil?
        invalid_properties.push('invalid value for "total_credits", total_credits cannot be nil.')
      end

      if @credits_for_payout.nil?
        invalid_properties.push('invalid value for "credits_for_payout", credits_for_payout cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @time_stamp.nil?
      return false if @session_counter.nil?
      return false if @manager_group.nil?
      return false if @normal_credits.nil?
      return false if @pure_gift_credits.nil?
      return false if @pre_gift_credits.nil?
      return false if @total_credits.nil?
      return false if @credits_for_payout.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          time_stamp == o.time_stamp &&
          tag_nr == o.tag_nr &&
          session_counter == o.session_counter &&
          manager_group == o.manager_group &&
          normal_credits == o.normal_credits &&
          pure_gift_credits == o.pure_gift_credits &&
          pre_gift_credits == o.pre_gift_credits &&
          total_credits == o.total_credits &&
          credits_for_payout == o.credits_for_payout &&
          system_flags == o.system_flags &&
          project_fields == o.project_fields
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [time_stamp, tag_nr, session_counter, manager_group, normal_credits, pure_gift_credits, pre_gift_credits, total_credits, credits_for_payout, system_flags, project_fields].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = GlobalEventTechnologyApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
