=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.77
=end

require 'date'

module GlobalEventTechnologyApiClient
  class SiteConfigNotReadyErrorType
    AC_ENTRY_AREA_MISSING = 'AcEntryAreaMissing'.freeze
    AC_EXIT_AREA_MISSING = 'AcExitAreaMissing'.freeze
    AC_SELL_PRODUCT_DEFAULT_MENU_ITEM_MISSING = 'AcSellProductDefaultMenuItemMissing'.freeze
    CHIPS_MISSING = 'ChipsMissing'.freeze
    MENU_MISSING = 'MenuMissing'.freeze
    PAYMENT_TYPES_MISSING = 'PaymentTypesMissing'.freeze
    SELF_SERVICE_CARD_PAYMENT_TYPE_MISSING = 'SelfServiceCardPaymentTypeMissing'.freeze
    SELF_SERVICE_CASH_PAYMENT_TYPE_MISSING = 'SelfServiceCashPaymentTypeMissing'.freeze
    SELF_SERVICE_CASHLESS_PAYMENT_TYPE_MISSING = 'SelfServiceCashlessPaymentTypeMissing'.freeze
    TICKET_TYPE_LABELS_MISSING = 'TicketTypeLabelsMissing'.freeze
    TIP_CONFIG_MISSING = 'TipConfigMissing'.freeze
    CUSTOM_FIELD_CONFIG_MISSING = 'CustomFieldConfigMissing'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = SiteConfigNotReadyErrorType.constants.select { |c| SiteConfigNotReadyErrorType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #SiteConfigNotReadyErrorType" if constantValues.empty?
      value
    end
  end
end
