=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'date'

module GlobalEventTechnologyApiClient
  class TicketValidationModel
    attr_accessor :id

    attr_accessor :ticket_id

    attr_accessor :barcode

    attr_accessor :ticket_type_id

    attr_accessor :ticket_declared_valid

    attr_accessor :ticket_valid

    attr_accessor :is_reversal

    attr_accessor :visits

    attr_accessor :unit_id

    attr_accessor :site_id

    attr_accessor :unit_name

    attr_accessor :site_name

    attr_accessor :worker_tag_nr

    attr_accessor :error_message

    attr_accessor :generic_data

    attr_accessor :update_date

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'ticket_id' => :'ticketId',
        :'barcode' => :'barcode',
        :'ticket_type_id' => :'ticketTypeId',
        :'ticket_declared_valid' => :'ticketDeclaredValid',
        :'ticket_valid' => :'ticketValid',
        :'is_reversal' => :'isReversal',
        :'visits' => :'visits',
        :'unit_id' => :'unitId',
        :'site_id' => :'siteId',
        :'unit_name' => :'unitName',
        :'site_name' => :'siteName',
        :'worker_tag_nr' => :'workerTagNr',
        :'error_message' => :'errorMessage',
        :'generic_data' => :'genericData',
        :'update_date' => :'updateDate'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Object',
        :'ticket_id' => :'Object',
        :'barcode' => :'Object',
        :'ticket_type_id' => :'Object',
        :'ticket_declared_valid' => :'Object',
        :'ticket_valid' => :'Object',
        :'is_reversal' => :'Object',
        :'visits' => :'Object',
        :'unit_id' => :'Object',
        :'site_id' => :'Object',
        :'unit_name' => :'Object',
        :'site_name' => :'Object',
        :'worker_tag_nr' => :'Object',
        :'error_message' => :'Object',
        :'generic_data' => :'Object',
        :'update_date' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `GlobalEventTechnologyApiClient::TicketValidationModel` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `GlobalEventTechnologyApiClient::TicketValidationModel`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'ticket_id')
        self.ticket_id = attributes[:'ticket_id']
      end

      if attributes.key?(:'barcode')
        self.barcode = attributes[:'barcode']
      end

      if attributes.key?(:'ticket_type_id')
        self.ticket_type_id = attributes[:'ticket_type_id']
      end

      if attributes.key?(:'ticket_declared_valid')
        self.ticket_declared_valid = attributes[:'ticket_declared_valid']
      end

      if attributes.key?(:'ticket_valid')
        self.ticket_valid = attributes[:'ticket_valid']
      end

      if attributes.key?(:'is_reversal')
        self.is_reversal = attributes[:'is_reversal']
      end

      if attributes.key?(:'visits')
        self.visits = attributes[:'visits']
      end

      if attributes.key?(:'unit_id')
        self.unit_id = attributes[:'unit_id']
      end

      if attributes.key?(:'site_id')
        self.site_id = attributes[:'site_id']
      end

      if attributes.key?(:'unit_name')
        self.unit_name = attributes[:'unit_name']
      end

      if attributes.key?(:'site_name')
        self.site_name = attributes[:'site_name']
      end

      if attributes.key?(:'worker_tag_nr')
        self.worker_tag_nr = attributes[:'worker_tag_nr']
      end

      if attributes.key?(:'error_message')
        self.error_message = attributes[:'error_message']
      end

      if attributes.key?(:'generic_data')
        self.generic_data = attributes[:'generic_data']
      end

      if attributes.key?(:'update_date')
        self.update_date = attributes[:'update_date']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @ticket_declared_valid.nil?
        invalid_properties.push('invalid value for "ticket_declared_valid", ticket_declared_valid cannot be nil.')
      end

      if @ticket_valid.nil?
        invalid_properties.push('invalid value for "ticket_valid", ticket_valid cannot be nil.')
      end

      if @is_reversal.nil?
        invalid_properties.push('invalid value for "is_reversal", is_reversal cannot be nil.')
      end

      if @visits.nil?
        invalid_properties.push('invalid value for "visits", visits cannot be nil.')
      end

      if @update_date.nil?
        invalid_properties.push('invalid value for "update_date", update_date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @ticket_declared_valid.nil?
      return false if @ticket_valid.nil?
      return false if @is_reversal.nil?
      return false if @visits.nil?
      return false if @update_date.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          ticket_id == o.ticket_id &&
          barcode == o.barcode &&
          ticket_type_id == o.ticket_type_id &&
          ticket_declared_valid == o.ticket_declared_valid &&
          ticket_valid == o.ticket_valid &&
          is_reversal == o.is_reversal &&
          visits == o.visits &&
          unit_id == o.unit_id &&
          site_id == o.site_id &&
          unit_name == o.unit_name &&
          site_name == o.site_name &&
          worker_tag_nr == o.worker_tag_nr &&
          error_message == o.error_message &&
          generic_data == o.generic_data &&
          update_date == o.update_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, ticket_id, barcode, ticket_type_id, ticket_declared_valid, ticket_valid, is_reversal, visits, unit_id, site_id, unit_name, site_name, worker_tag_nr, error_message, generic_data, update_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        GlobalEventTechnologyApiClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
