=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.51-SNAPSHOT

=end

require 'date'

module GlobalEventTechnologyApiClient
  class TicketValidationModel
    attr_accessor :id

    attr_accessor :ticket_id

    attr_accessor :barcode

    attr_accessor :ticket_type_id

    attr_accessor :ticket_declared_valid

    attr_accessor :ticket_valid

    attr_accessor :is_reversal

    attr_accessor :visits

    attr_accessor :unit_id

    attr_accessor :site_id

    attr_accessor :unit_name

    attr_accessor :site_name

    attr_accessor :worker_tag_nr

    attr_accessor :error_message

    attr_accessor :generic_data

    attr_accessor :update_date

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'ticket_id' => :'ticketId',
        :'barcode' => :'barcode',
        :'ticket_type_id' => :'ticketTypeId',
        :'ticket_declared_valid' => :'ticketDeclaredValid',
        :'ticket_valid' => :'ticketValid',
        :'is_reversal' => :'isReversal',
        :'visits' => :'visits',
        :'unit_id' => :'unitId',
        :'site_id' => :'siteId',
        :'unit_name' => :'unitName',
        :'site_name' => :'siteName',
        :'worker_tag_nr' => :'workerTagNr',
        :'error_message' => :'errorMessage',
        :'generic_data' => :'genericData',
        :'update_date' => :'updateDate'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'String',
        :'ticket_id' => :'String',
        :'barcode' => :'String',
        :'ticket_type_id' => :'String',
        :'ticket_declared_valid' => :'BOOLEAN',
        :'ticket_valid' => :'BOOLEAN',
        :'is_reversal' => :'BOOLEAN',
        :'visits' => :'Integer',
        :'unit_id' => :'String',
        :'site_id' => :'String',
        :'unit_name' => :'String',
        :'site_name' => :'String',
        :'worker_tag_nr' => :'String',
        :'error_message' => :'String',
        :'generic_data' => :'String',
        :'update_date' => :'DateTime'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'ticketId')
        self.ticket_id = attributes[:'ticketId']
      end

      if attributes.has_key?(:'barcode')
        self.barcode = attributes[:'barcode']
      end

      if attributes.has_key?(:'ticketTypeId')
        self.ticket_type_id = attributes[:'ticketTypeId']
      end

      if attributes.has_key?(:'ticketDeclaredValid')
        self.ticket_declared_valid = attributes[:'ticketDeclaredValid']
      end

      if attributes.has_key?(:'ticketValid')
        self.ticket_valid = attributes[:'ticketValid']
      end

      if attributes.has_key?(:'isReversal')
        self.is_reversal = attributes[:'isReversal']
      end

      if attributes.has_key?(:'visits')
        self.visits = attributes[:'visits']
      end

      if attributes.has_key?(:'unitId')
        self.unit_id = attributes[:'unitId']
      end

      if attributes.has_key?(:'siteId')
        self.site_id = attributes[:'siteId']
      end

      if attributes.has_key?(:'unitName')
        self.unit_name = attributes[:'unitName']
      end

      if attributes.has_key?(:'siteName')
        self.site_name = attributes[:'siteName']
      end

      if attributes.has_key?(:'workerTagNr')
        self.worker_tag_nr = attributes[:'workerTagNr']
      end

      if attributes.has_key?(:'errorMessage')
        self.error_message = attributes[:'errorMessage']
      end

      if attributes.has_key?(:'genericData')
        self.generic_data = attributes[:'genericData']
      end

      if attributes.has_key?(:'updateDate')
        self.update_date = attributes[:'updateDate']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @ticket_declared_valid.nil?
        invalid_properties.push('invalid value for "ticket_declared_valid", ticket_declared_valid cannot be nil.')
      end

      if @ticket_valid.nil?
        invalid_properties.push('invalid value for "ticket_valid", ticket_valid cannot be nil.')
      end

      if @is_reversal.nil?
        invalid_properties.push('invalid value for "is_reversal", is_reversal cannot be nil.')
      end

      if @visits.nil?
        invalid_properties.push('invalid value for "visits", visits cannot be nil.')
      end

      if @update_date.nil?
        invalid_properties.push('invalid value for "update_date", update_date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @ticket_declared_valid.nil?
      return false if @ticket_valid.nil?
      return false if @is_reversal.nil?
      return false if @visits.nil?
      return false if @update_date.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          ticket_id == o.ticket_id &&
          barcode == o.barcode &&
          ticket_type_id == o.ticket_type_id &&
          ticket_declared_valid == o.ticket_declared_valid &&
          ticket_valid == o.ticket_valid &&
          is_reversal == o.is_reversal &&
          visits == o.visits &&
          unit_id == o.unit_id &&
          site_id == o.site_id &&
          unit_name == o.unit_name &&
          site_name == o.site_name &&
          worker_tag_nr == o.worker_tag_nr &&
          error_message == o.error_message &&
          generic_data == o.generic_data &&
          update_date == o.update_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, ticket_id, barcode, ticket_type_id, ticket_declared_valid, ticket_valid, is_reversal, visits, unit_id, site_id, unit_name, site_name, worker_tag_nr, error_message, generic_data, update_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = GlobalEventTechnologyApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
