=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'date'

module GlobalEventTechnologyApiClient
  class TransactionTypeEnumModel
    UNKNOWN = 'Unknown'.freeze
    CREDIT = 'Credit'.freeze
    CREDIT_REFUND = 'CreditRefund'.freeze
    POS = 'Pos'.freeze
    EXIT_TAG = 'ExitTag'.freeze
    INFO = 'Info'.freeze
    PAYOUT = 'Payout'.freeze
    POS_REFUND = 'PosRefund'.freeze
    ACCREDIT = 'Accredit'.freeze
    TICKET_VALIDATION = 'TicketValidation'.freeze
    AC_CHECK = 'AcCheck'.freeze
    REQUEST = 'Request'.freeze
    PREPARE = 'Prepare'.freeze
    ONLINE_PAYOUT = 'OnlinePayout'.freeze
    ONLINE_SHOP = 'OnlineShop'.freeze
    DEVICE_RETURNED = 'DeviceReturned'.freeze
    TAG_RESTORE = 'TagRestore'.freeze
    IS_ALIVE = 'IsAlive'.freeze
    DOCUMENT = 'Document'.freeze
    MY_REGISTER_PAYMENT_METHOD = 'MyRegisterPaymentMethod'.freeze
    SHIPMENT_START = 'ShipmentStart'.freeze
    SHIPMENT_END = 'ShipmentEnd'.freeze
    OPENING_STOCK = 'OpeningStock'.freeze
    INTERMEDIATE_STOCK = 'IntermediateStock'.freeze
    CLOSING_STOCK = 'ClosingStock'.freeze
    FINAL_STOCK = 'FinalStock'.freeze
    LOSS = 'Loss'.freeze
    STAFF_CHECK = 'StaffCheck'.freeze
    STOCK_CHECK = 'StockCheck'.freeze
    NEW_TAG = 'NewTag'.freeze
    TICKET_ONLINE_ACTIVATION = 'TicketOnlineActivation'.freeze
    REDEEM_PRODUCT_VOUCHER = 'RedeemProductVoucher'.freeze
    TAG_RESTORE_TO_NEW_TAG = 'TagRestoreToNewTag'.freeze
    REFERENCE_STOCK = 'ReferenceStock'.freeze
    API_ORDER = 'ApiOrder'.freeze
    CORRECTION = 'Correction'.freeze
    TAG_RESTORE_FROM_OLD_TAG = 'TagRestoreFromOldTag'.freeze
    BUSINESS_CASE_FROM = 'BusinessCaseFrom'.freeze
    BUSINESS_CASE_TO = 'BusinessCaseTo'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TransactionTypeEnumModel.constants.select { |c| TransactionTypeEnumModel::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TransactionTypeEnumModel" if constantValues.empty?
      value
    end
  end
end
