=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.51-SNAPSHOT

=end

require 'date'

module GlobalEventTechnologyApiClient
  class WorkTimeModel
    attr_accessor :id

    attr_accessor :update_date

    attr_accessor :unit_id

    attr_accessor :worker_tag_session

    attr_accessor :begin_stamp_id

    attr_accessor :begin_date

    attr_accessor :begin_cost_center_id

    attr_accessor :begin_cost_center_name

    attr_accessor :begin_site_id

    attr_accessor :begin_site_name

    attr_accessor :begin_note

    attr_accessor :end_stamp_id

    attr_accessor :end_date

    attr_accessor :end_cost_center_id

    attr_accessor :end_cost_center_name

    attr_accessor :end_site_id

    attr_accessor :end_site_name

    attr_accessor :end_note

    attr_accessor :hours

    attr_accessor :seconds

    attr_accessor :rating

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'update_date' => :'updateDate',
        :'unit_id' => :'unitId',
        :'worker_tag_session' => :'workerTagSession',
        :'begin_stamp_id' => :'beginStampId',
        :'begin_date' => :'beginDate',
        :'begin_cost_center_id' => :'beginCostCenterId',
        :'begin_cost_center_name' => :'beginCostCenterName',
        :'begin_site_id' => :'beginSiteId',
        :'begin_site_name' => :'beginSiteName',
        :'begin_note' => :'beginNote',
        :'end_stamp_id' => :'endStampId',
        :'end_date' => :'endDate',
        :'end_cost_center_id' => :'endCostCenterId',
        :'end_cost_center_name' => :'endCostCenterName',
        :'end_site_id' => :'endSiteId',
        :'end_site_name' => :'endSiteName',
        :'end_note' => :'endNote',
        :'hours' => :'hours',
        :'seconds' => :'seconds',
        :'rating' => :'rating'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'id' => :'String',
        :'update_date' => :'DateTime',
        :'unit_id' => :'String',
        :'worker_tag_session' => :'String',
        :'begin_stamp_id' => :'String',
        :'begin_date' => :'DateTime',
        :'begin_cost_center_id' => :'String',
        :'begin_cost_center_name' => :'String',
        :'begin_site_id' => :'String',
        :'begin_site_name' => :'String',
        :'begin_note' => :'String',
        :'end_stamp_id' => :'String',
        :'end_date' => :'DateTime',
        :'end_cost_center_id' => :'String',
        :'end_cost_center_name' => :'String',
        :'end_site_id' => :'String',
        :'end_site_name' => :'String',
        :'end_note' => :'String',
        :'hours' => :'Float',
        :'seconds' => :'Float',
        :'rating' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.has_key?(:'updateDate')
        self.update_date = attributes[:'updateDate']
      end

      if attributes.has_key?(:'unitId')
        self.unit_id = attributes[:'unitId']
      end

      if attributes.has_key?(:'workerTagSession')
        self.worker_tag_session = attributes[:'workerTagSession']
      end

      if attributes.has_key?(:'beginStampId')
        self.begin_stamp_id = attributes[:'beginStampId']
      end

      if attributes.has_key?(:'beginDate')
        self.begin_date = attributes[:'beginDate']
      end

      if attributes.has_key?(:'beginCostCenterId')
        self.begin_cost_center_id = attributes[:'beginCostCenterId']
      end

      if attributes.has_key?(:'beginCostCenterName')
        self.begin_cost_center_name = attributes[:'beginCostCenterName']
      end

      if attributes.has_key?(:'beginSiteId')
        self.begin_site_id = attributes[:'beginSiteId']
      end

      if attributes.has_key?(:'beginSiteName')
        self.begin_site_name = attributes[:'beginSiteName']
      end

      if attributes.has_key?(:'beginNote')
        self.begin_note = attributes[:'beginNote']
      end

      if attributes.has_key?(:'endStampId')
        self.end_stamp_id = attributes[:'endStampId']
      end

      if attributes.has_key?(:'endDate')
        self.end_date = attributes[:'endDate']
      end

      if attributes.has_key?(:'endCostCenterId')
        self.end_cost_center_id = attributes[:'endCostCenterId']
      end

      if attributes.has_key?(:'endCostCenterName')
        self.end_cost_center_name = attributes[:'endCostCenterName']
      end

      if attributes.has_key?(:'endSiteId')
        self.end_site_id = attributes[:'endSiteId']
      end

      if attributes.has_key?(:'endSiteName')
        self.end_site_name = attributes[:'endSiteName']
      end

      if attributes.has_key?(:'endNote')
        self.end_note = attributes[:'endNote']
      end

      if attributes.has_key?(:'hours')
        self.hours = attributes[:'hours']
      end

      if attributes.has_key?(:'seconds')
        self.seconds = attributes[:'seconds']
      end

      if attributes.has_key?(:'rating')
        self.rating = attributes[:'rating']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @update_date.nil?
        invalid_properties.push('invalid value for "update_date", update_date cannot be nil.')
      end

      if @unit_id.nil?
        invalid_properties.push('invalid value for "unit_id", unit_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @id.nil?
      return false if @update_date.nil?
      return false if @unit_id.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          update_date == o.update_date &&
          unit_id == o.unit_id &&
          worker_tag_session == o.worker_tag_session &&
          begin_stamp_id == o.begin_stamp_id &&
          begin_date == o.begin_date &&
          begin_cost_center_id == o.begin_cost_center_id &&
          begin_cost_center_name == o.begin_cost_center_name &&
          begin_site_id == o.begin_site_id &&
          begin_site_name == o.begin_site_name &&
          begin_note == o.begin_note &&
          end_stamp_id == o.end_stamp_id &&
          end_date == o.end_date &&
          end_cost_center_id == o.end_cost_center_id &&
          end_cost_center_name == o.end_cost_center_name &&
          end_site_id == o.end_site_id &&
          end_site_name == o.end_site_name &&
          end_note == o.end_note &&
          hours == o.hours &&
          seconds == o.seconds &&
          rating == o.rating
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [id, update_date, unit_id, worker_tag_session, begin_stamp_id, begin_date, begin_cost_center_id, begin_cost_center_name, begin_site_id, begin_site_name, begin_note, end_stamp_id, end_date, end_cost_center_id, end_cost_center_name, end_site_id, end_site_name, end_note, hours, seconds, rating].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = GlobalEventTechnologyApiClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
