=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.4

=end

require 'spec_helper'
require 'json'

# Unit tests for GlobalEventTechnologyApiClient::ProjectProductsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProjectProductsApi' do
  before do
    # run before each test
    @instance = GlobalEventTechnologyApiClient::ProjectProductsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectProductsApi' do
    it 'should create an instance of ProjectProductsApi' do
      expect(@instance).to be_instance_of(GlobalEventTechnologyApiClient::ProjectProductsApi)
    end
  end

  # unit tests for project_products_create_or_update_product
  # @param project_id 
  # @param product_list_id 
  # @param product_id 
  # @param args 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'project_products_create_or_update_product test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_products_delete_area
  # @param project_id 
  # @param product_list_id 
  # @param product_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'project_products_delete_area test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_products_get_all
  # @param project_id 
  # @param product_list_id 
  # @param [Hash] opts the optional parameters
  # @return [ArrayResultOfProductsModel]
  describe 'project_products_get_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_products_get_by_id
  # @param project_id 
  # @param product_list_id 
  # @param product_id 
  # @param [Hash] opts the optional parameters
  # @return [ProductsModel]
  describe 'project_products_get_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
