=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.57
=end

require 'spec_helper'
require 'json'

# Unit tests for GlobalEventTechnologyApiClient::ProjectTransactionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProjectTransactionsApi' do
  before do
    # run before each test
    @instance = GlobalEventTechnologyApiClient::ProjectTransactionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectTransactionsApi' do
    it 'should create an instance of ProjectTransactionsApi' do
      expect(@instance).to be_instance_of(GlobalEventTechnologyApiClient::ProjectTransactionsApi)
    end
  end

  # unit tests for project_transactions_get_all
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :_next 
  # @option opts [Array<String>] :site_ids A string containing an array of siteIds delimited by a comma
  # @option opts [Array<String>] :unit_ids A string containing an array of unitIds delimited by a comma
  # @option opts [Array<String>] :transaction_item_types A string containing an array of transactionItemTypes delimited by a comma
  # @option opts [String] :received_from A string representing a DateTimeOffset to filter transactions from a specific receiveDate
  # @option opts [String] :received_until A string representing a DateTimeOffset to filter transactions to a specific receiveDate
  # @return [ArrayResultOfTransactionModel]
  describe 'project_transactions_get_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_transactions_get_by_id
  # @param project_id 
  # @param transaction_id 
  # @param [Hash] opts the optional parameters
  # @return [TransactionModel]
  describe 'project_transactions_get_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
