=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for GlobalEventTechnologyApiClient::ProjectTagBlacklistsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProjectTagBlacklistsApi' do
  before do
    # run before each test
    @instance = GlobalEventTechnologyApiClient::ProjectTagBlacklistsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectTagBlacklistsApi' do
    it 'should create an instance of ProjectTagBlacklistsApi' do
      expect(@instance).to be_instance_of(GlobalEventTechnologyApiClient::ProjectTagBlacklistsApi)
    end
  end

  # unit tests for project_tag_blacklists_get_all
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :_next 
  # @return [ArrayResultOfTagBlacklistModel]
  describe 'project_tag_blacklists_get_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_tag_blacklists_get_tag_session_entries
  # @param project_id 
  # @param tag_nr 
  # @param tag_session_counter 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :_next 
  # @return [ArrayResultOfTagBlacklistModel]
  describe 'project_tag_blacklists_get_tag_session_entries test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for project_tag_blacklists_update_black_list_for_tag
  # @param body 
  # @param project_id 
  # @param tag_nr 
  # @param tag_session_counter 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'project_tag_blacklists_update_black_list_for_tag test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
