=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.55
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GlobalEventTechnologyApiClient::AreaCountedWorkerTypeEnum
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AreaCountedWorkerTypeEnum' do
  before do
    # run before each test
    @instance = GlobalEventTechnologyApiClient::AreaCountedWorkerTypeEnum.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AreaCountedWorkerTypeEnum' do
    it 'should create an instance of AreaCountedWorkerTypeEnum' do
      expect(@instance).to be_instance_of(GlobalEventTechnologyApiClient::AreaCountedWorkerTypeEnum)
    end
  end
end
