=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.77
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GlobalEventTechnologyApiClient::ExternalRefundTransactionRequestItemRefundModel
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExternalRefundTransactionRequestItemRefundModel' do
  before do
    # run before each test
    @instance = GlobalEventTechnologyApiClient::ExternalRefundTransactionRequestItemRefundModel.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExternalRefundTransactionRequestItemRefundModel' do
    it 'should create an instance of ExternalRefundTransactionRequestItemRefundModel' do
      expect(@instance).to be_instance_of(GlobalEventTechnologyApiClient::ExternalRefundTransactionRequestItemRefundModel)
    end
  end
  describe 'test attribute "item_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "refund_count"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
