=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.77
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GlobalEventTechnologyApiClient::ExternalRefundTransactionRequestModel
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExternalRefundTransactionRequestModel' do
  before do
    # run before each test
    @instance = GlobalEventTechnologyApiClient::ExternalRefundTransactionRequestModel.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExternalRefundTransactionRequestModel' do
    it 'should create an instance of ExternalRefundTransactionRequestModel' do
      expect(@instance).to be_instance_of(GlobalEventTechnologyApiClient::ExternalRefundTransactionRequestModel)
    end
  end
  describe 'test attribute "new_transaction_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "item_refunds"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "note"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
