=begin
#Project API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for GlobalEventTechnologyApiClient::ExternalSiteTypeModel
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ExternalSiteTypeModel' do
  before do
    # run before each test
    @instance = GlobalEventTechnologyApiClient::ExternalSiteTypeModel.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExternalSiteTypeModel' do
    it 'should create an instance of ExternalSiteTypeModel' do
      expect(@instance).to be_instance_of(GlobalEventTechnologyApiClient::ExternalSiteTypeModel)
    end
  end
end
