name: Ruby

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.3'
          - '3.2.0'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rspec

  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.0
        bundler-cache: true

    - name: Publish gem
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        GIT_SHA: ${{ github.sha }}
        OWNER: ${{ github.repository_owner }}
      run:
       |
        set -xe

        mkdir -p ~/.gem
        touch ~/.gem/credentials
        chmod 600 ~/.gem/credentials
        printf -- "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}\n" > ~/.gem/credentials
        ruby .github/workflows/set_version.rb
        gem build *.gemspec
        gem push *.gem --key github --host https://rubygems.pkg.github.com/${OWNER}
